name: Deployment workflow (container)
on:
  push:
    branches:
      - master
env:
    CACHE_KEY: node-deps
    MONGODB_DB_NAME: gha-demo
jobs:
    test-job:
        environment: testing
        runs-on: ubuntu-latest
        container:
            image: node:16
        env:
            MONGODB_CONNECTION_PROTOCOL: mongodb
            MONGODB_CLUSTER_ADDRESS: mongodb-service   
            MONGODB_USERNAME: root      
            MONGODB_PASSWORD: example      
            PORT: 8080
        services:
            mongodb-service:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: root
                    MONGO_INITDB_ROOT_PASSWORD: example
                ports:
                    - 27017:27017
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cache Dependencies
              uses: actions/cache@v2
              with:
                path: ~/.npm
                key: npm-deps-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm install
            - name: Run Server
              run: npm start & npx wait-on http://127.0.0.1:$PORT  
            - name: Run tests
              run: npm test 
            - name: Output Info
              run: echo "Mongo DB Username = ${{ env.MONGODB_USERNAME }}"  